### ISSUE TITLE
Players should not have the option to sell coins

### ISSUE THREAD

**Issue by srichter** [delaford/game#100]
A continuation of discussion from https://github.com/delaford/game/issues/95#issuecomment-537799901

**What is the current behavior?**
When in a shop, a player is presented with the option to sell coins to a shop, even though it is prohibited.

**If the current behavior is a bug, please provide the exact steps to reproduce.**
1. Have coins in your inventory
2. Start a trade with a store
3. Open the context menu on coins
4. The option to sell coins is presented

**What is the expected behavior?**
There should be no option to sell coins

**Additional context**
Thinking about the best way to remedy this. Right now the actions for coins come from it being defined as a resource. If there are also going to be quest items that are unsellable, it may make sense to define a new type of preset which doesn't include sell. Or maybe it makes sense to have the ability to pass a parameter to presetActions which will contains actions to be removed from the resulting array. Another way would be to check for the item being prohibited in the frontend (will it see that?) and just not display the actions there, but that seems the clunkiest method to me.

**Comment by naknode** [comment]
The reason I leave the `Sell` option in is because it's less work and you just prohibit it in the backend and spit out a `"Sorry, can't sell"` message. I do get where you're going. Going with this approach would be more work on the front-end too.

There is no expected behavior but from what I've seen many games either show it or don't. Right now, we are showing it but not allowing to sell it. Which i think keeps the flow going like I said.

**Comment by aahvocado** [comment]
I know this is a minor thing but I went ahead and took a crack at it to see how everything worked.
