### ISSUE TITLE
Uncaught SyntaxError: Unexpected token _ in JSON at position 0 during npm serve

### ISSUE THREAD

**Issue by naknode** [delaford/game#55]
**What is the current behavior?**

When you follow the instructions to install on any Windows machine, you go to the webpage after `npm run serve` and you get `Uncaught SyntaxError: Unexpected token _ in JSON at position 0`

**If the current behavior is a bug, please provide the exact steps to reproduce.**

1. git clone
2. cd game
3. npm install
4. npm run serve

**What is the expected behavior?**

For the game to run without errors on a Windows machine

**Additional context**

**Comment by naknode** [comment]
After having downloaded it on my Mac again, sometimes, it has done this so this error is not only to Window but I think rather if you are using or recently used an app that uses VueX (persisted state). Not 100% sure but I think that's it.

**Comment by naknode** [comment]
Would love some extra eyes on this. This is a peculiar issue which I have not had been able to pinpoint... not sure if it's stopping people from downloading the first since I know others have been able to download and play...

**Comment by erezvish** [comment]
I'm using a window machine and I remember having something like this a couple of weeks ago when I downloaded for the first time, but not sure how I resolved it.

Anyway, I tried reproducing it by installing from scratch in a different folder and running and this did not happen. Maybe the problem resolved itself unintentionally via another fix?

I am encountering some other problems though which are windows related:

1. package.json **"clean-server": "rm -rf build && mkdir build"** will fail, since the windows command is rd -r if I'm not mistaken. However, switching the command results in a "cannot find directory" problem.

2. when running with npm run serve a lot of line breaks errors are found. This is due to windows line break being of type CRLF instead of LF. this can be mitigated in one of two ways: 

- change the editor's default line break to LF (easy in vscode which I use). This has to be done in every file.

- add a new eslint rule, something along the lines of **"linebreak-style": ["error", process.env.NODE_ENV === 'prod' ? "unix" : "windows]"**. I'm not quite sure how that will work for mac users though.

**Comment by naknode** [comment]
Interesting. I will have to download it and check it out. As for the rm rf problem... I knew that day would come. There might be a tool that converts every file to LF...

**Comment by erezvish** [comment]
No worries, for now what I'll do is just have the local changes I need due to windows in my main dev branch, and pull request from a commit branch that has those changes cancelled. Seems to work fine

**Comment by naknode** [comment]
Alright, thanks for your patience @erezvish . I am sure there is way to resolve this mess and for now, I've contained it to #73.

**Comment by naknode** [comment]
It seems by switching npm packages to another (more-starred) package for persist state has made this work.
